"""add description

Revision ID: 1d93e0833eaf
Revises: 
Create Date: 2023-07-06 14:41:16.159751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d93e0833eaf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_template_data', sa.Column('description', sa.String(), nullable=True, comment='用例描述'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_template_data', 'description')
    # ### end Alembic commands ###
