"""ui列表增加成功失败记数

Revision ID: 746eaba3c246
Revises: 87ac07f0588b
Create Date: 2023-07-11 10:18:15.762985

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '746eaba3c246'
down_revision = '87ac07f0588b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playwright_temp', sa.Column('success', sa.Integer(), nullable=True, default=0, comment='成功次数'))
    op.add_column('playwright_temp', sa.Column('fail', sa.Integer(), nullable=True, default=0, comment='失败次数'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playwright_temp', 'fail')
    op.drop_column('playwright_temp', 'success')
    # ### end Alembic commands ###
