"""api测试列表增加成功失败记数

Revision ID: 87ac07f0588b
Revises: 1d93e0833eaf
Create Date: 2023-07-11 10:12:44.774046

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '87ac07f0588b'
down_revision = '1d93e0833eaf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case', sa.Column('success', sa.Integer(), nullable=True, default=0, comment='成功次数'))
    op.add_column('test_case', sa.Column('fail', sa.Integer(), nullable=True, default=0, comment='失败次数'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_case', 'fail')
    op.drop_column('test_case', 'success')
    # ### end Alembic commands ###
