"""模板表增加response_headers列

Revision ID: d96e5ab3132b
Revises: 746eaba3c246
Create Date: 2023-08-23 09:58:31.271136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd96e5ab3132b'
down_revision = '746eaba3c246'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_template_data', sa.Column('response_headers', sa.JSON(), nullable=True, comment='响应请求头'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_template_data', 'response_headers')
    # ### end Alembic commands ###
